n_estimators: 1000
max_depth: 8
num_leaves: 255
#num_leaves: 1000
learning_rate: 0.01
num_threads: 10
feature_fraction: 0.6
bagging_fraction: 0.6
bagging_freq: 5
cat_smooth: 10
max_bin: 255
# reg_alpha: 1
# reg_lambda: 1
random_state: 42
verbosity: -1