sampling_method: uniform
tree_method: hist
objective: reg:squarederror  
eval_metric: rmse
device: cpu
n_jobs: 16

learning_rate: 0.05 
lambda: 1
alpha: 1

subsample: 0.5
colsample_bytree: 0.5
colsample_bylevel: 0.5
colsample_bynode: 0.5

max_depth: 10 
max_leaves: 1023      
max_bin: 255 

random_state: 42               
verbosity: 0